x-podman:
  in_pod: false

services:
  dockns:
    container_name: dockns
    hostname: dockns
    image: docker.io/brenekh/dockns:0.5.0
    restart: unless-stopped
    networks:
      - traefik-proxy
    env_file:
      - .env
    environment:
      - DOCKER_HOST=tcp://podman-proxy:2375
    volumes:
      # - /var/run/podman/podman.sock:/var/run/docker.sock:ro
      - dockns-data:/data:Z
    labels:
      - "homepage.group=Utilities"
      - "homepage.name=DockNS"
      - "homepage.icon=mdi-anchor"
      - "homepage.description=DockNS Record Orchestration"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://127.0.0.1:4104/health || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s

volumes:
  dockns-data:
    name: dockns-data

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy