launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3

local-address=0.0.0.0
local-port=53

api=yes
api-key=${PDNS_AUTH_API_KEY}
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=192.168.62.0/23,127.0.0.0/8

default-soa-content=ns1.lab.kemo.dev admin.lab.kemo.dev 0 10800 3600 604800 3600
