services:
  squid:
    image: quay.io/kenmoini/squid-proxy:latest
    container_name: squid
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./config/:/etc/squid/conf.d:ro,Z
      - /etc/pki/:/etc/pki/:ro
      - /opt/workdir/caas/outbound-proxy/data/cache/:/var/spool/squid/:Z
      - /opt/workdir/caas/outbound-proxy/data/logs/:/var/log/squid/:Z
      - /opt/workdir/caas/pika-pki/data/.pika-pki/public_bundles/certs/signing-ca.kemo-labs-squid-proxy-ca.cert.pem:/etc/squid/certs/ca.crt:ro
      - /opt/workdir/caas/pika-pki/data/.pika-pki/public_bundles/certs/signing-ca.kemo-labs-squid-proxy-ca.cert.pem.full-chain.pem:/etc/squid/certs/ca-bundle.crt:ro
      - /opt/workdir/caas/pika-pki/data/.pika-pki/roots/kemo-labs-root-certificate-authority/intermediate-ca/kemo-labs-intermediate-ca/signing-ca/kemo-labs-squid-proxy-ca/private/ca.key.pem:/etc/squid/certs/ca.key:ro
    networks:
      bridge42:
        ipv4_address: 192.168.42.11
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3128 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - "homepage.group=Services"
      - "homepage.name=Squid"
      - "homepage.icon=squidex.png"
      - "homepage.description=Outbound proxy server MiTM 3128, Passthrough 3129"
      - "homepage.href=http://proxy.lab.kemo.dev"

networks:
  bridge42:
    external: true
