services:
  traefik:
    image: docker.io/library/traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - OTEL_SERVICE_NAME=mgmt-traefik
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic/:/etc/traefik/dynamic/:ro
      - /opt/workdir/caas/traefik/data/storage:/etc/traefik/storage:Z
      - /opt/workdir/caas/pika-pki/data/.pika-pki/roots/kemo-labs-root-certificate-authority/certs/ca.cert.pem:/etc/traefik/certs/root_ca.crt:ro
      - /var/run/podman/podman.sock:/var/run/docker.sock:ro
      - /etc/pki/tls/cert.pem:/etc/ssl/certs/ca-certificates.crt:ro
    security_opt:
      - no-new-privileges:true
    networks:
      bridge42:
        ipv4_address: 192.168.42.10
      # traefik-proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.apps.lab.kemo.dev`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=stepca"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
      - "traefik.http.services.api@internal.loadbalancer.server.port=8080"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https,hsts-header"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.hsts-header.headers.sslredirect=true"
      - "homepage.group=Services"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.png"
      - "homepage.href=https://traefik.apps.lab.kemo.dev"
      - "homepage.description=Reverse Proxy and Load Balancer"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  # traefik-proxy:
  #   external: true
  bridge42:
    external: true
