services:
  nexus:
    image: docker.io/sonatype/nexus3:3.91.1-ubi
    container_name: nexus
    restart: unless-stopped
    env_file:
      - .env
    environment:
      INSTALL4J_ADD_VM_PARAMS: >-
        -Xms2g -Xmx4g
        -XX:MaxDirectMemorySize=2g
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      NEXUS_SECURITY_RANDOMPASSWORD: "false"
    volumes:
      - /opt/workdir/caas/nexus/data:/nexus-data
    labels:
      - "traefik.enable=true"
      # Nexus Web UI
      - "traefik.http.routers.nexus.rule=Host(`nexus.apps.lab.kemo.dev`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls=true"
      - "traefik.http.routers.nexus.tls.certresolver=stepca"
      - "traefik.http.routers.nexus.service=nexus"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "homepage.group=Utilities"
      - "homepage.name=Sonatype Nexus"
      - "homepage.icon=nexus.png"
      - "homepage.description=Nexus Repository Manager"
      - "homepage.href=https://nexus.apps.lab.kemo.dev"
      # Docker Registry (group)
      # - "traefik.http.routers.registry.rule=Host(`registry.apps.lab.kemo.dev`)"
      # - "traefik.http.routers.registry.entrypoints=websecure"
      # - "traefik.http.routers.registry.tls=true"
      # - "traefik.http.routers.registry.tls.certresolver=stepca"
      # - "traefik.http.routers.registry.service=registry"
      # - "traefik.http.services.registry.loadbalancer.server.port=8084"
    networks:
      bridge42:
        ipv4_address: 192.168.42.21
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  bridge42:
    external: true
