- AI:
  - Hermes:
      href: "https://hermes.apps.lab.kemo.dev/"
      icon: "https://hermes-agent.nousresearch.com/docs/img/logo.png"
      description: "Agentic Harness"

- Cockpit:
  - Tardis:
      href: "https://tardis.hosts.lab.kemo.dev:9090/"
      icon: "si-cockpit"
      description: "Primary Lab Host"
  - Galactica:
      href: "https://galactica.moini.mannor:9090/"
      icon: "si-cockpit"
      description: "Primary Home Host"
  - Normandy:
      href: "https://normandy.hosts.lab.kemo.dev:9090/"
      icon: "si-cockpit"
      description: "Secondary Lab Host"

- Home Automation:
  - Home Assistant:
      href: "https://home-assistant.apps.lab.kemo.dev/"
      icon: "si-homeassistant"
      description: "Smart Home Automation Engine"

- OOBM:
  - Endurance:
      href: "https://endurance.mgmt.kemo.labs/"
      icon: "si-supermicro"
      description: "OOBM at 192.168.46.49"
  - Raza:
      href: "https://raza.mgmt.kemo.labs/"
      icon: "si-supermicro"
      description: "OOBM at 192.168.46.40"
  - Suki:
      href: "https://suki.mgmt.kemo.labs/"
      icon: "si-supermicro"
      description: "OOBM at 192.168.46.46"

- Services:
  - ESXi:
      href: "https://rocinante.lab.kemo.dev/"
      description: "VMware ESXi Hypervisor"
      icon: "si-vmware"
  - vCenter:
      href: "https://vcenter.lab.kemo.dev/"
      description: "VMware vCenter Server"
      icon: "si-vmware"
  - Deep Thought NAS:
      href: "https://deep-thought.lab.kemo.dev/"
      description: "Bulk NAS"
      icon: "si-truenas"
