- Infrastructure:
    - Traefik:
        icon: traefik.svg
        href: https://traefik.lab.kemo.dev
        description: Reverse Proxy & Load Balancer
        widget:
          type: traefik
          url: http://192.168.62.10:8080

    - Pi-hole:
        icon: pi-hole.svg
        href: https://pihole.lab.kemo.dev
        description: DNS Ad Blocking
        widget:
          type: pihole
          url: http://192.168.62.4
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

    - PeaNUT:
        icon: peanut.svg
        href: https://peanut.lab.kemo.dev
        description: UPS Monitoring
        widget:
          type: peanut
          url: http://192.168.62.12:8081

    - Netboot.xyz:
        icon: netboot-xyz.svg
        href: https://netboot.lab.kemo.dev
        description: Network Boot Server

- Network:
    - OpenSpeedTest:
        icon: openspeedtest.svg
        href: https://speedtest.lab.kemo.dev
        description: Network Speed Test

    - Squid Proxy:
        icon: mdi-server-network
        href: http://192.168.62.11:3128
        description: Outbound HTTP Proxy

    - PowerDNS:
        icon: powerdns.svg
        href: http://192.168.62.2:8081
        description: Authoritative DNS
