title: Homelab Dashboard
description: Internal dashboard for Kemo Labs
language: en
hideVersion: true
showStats: true

startUrl: https://dashboard.apps.lab.kemo.dev
base: https://dashboard.apps.lab.kemo.dev
target: _blank

logpath: /data/logs

theme: dark
color: slate
useEqualHeights: true
headerStyle: boxed

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: false
  provider: duckduckgo
