title: Homelab Dashboard
description: Internal dashboard for Kemo Labs
language: en
hideVersion: true
showStats: true

startUrl: https://dashboard.apps.lab.kemo.dev
base: https://dashboard.apps.lab.kemo.dev
target: _blank

logpath: /data/logs

theme: dark
color: slate
background:
  image: /assets/background.jpeg
  opacity: 50

useEqualHeights: true
headerStyle: boxed

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: false
  provider: duckduckgo

layout:
  Cockpit:
    style: row
    columns: 4
  Databases:
    style: row
    columns: 4
  DNS:
    style: row
    columns: 4
  Identity & Secrets:
    style: row
    columns: 4
  Observability:
    style: row
    columns: 4
  OOBM:
    style: row
    columns: 4
  Paperless:
    style: row
    columns: 4
  Services:
    style: row
    columns: 4
  Utilities:
    style: row
    columns: 4