apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://o11y-prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: "Trace: $${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://o11y-tempo:3200
    access: proxy
    editable: true
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "loki"
        query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
        tags:
          - key: "service.name"
            value: "service_name"

      serviceMap:
        datasourceUid: "prometheus"
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "loki"

  - name: Loki
    type: loki
    uid: loki
    url: http://o11y-loki:3100
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - name: "trace_id"
          matcherType: "label"
          matcherRegex: "trace_id"
          url: "$${__value.raw}"
          datasourceUid: "tempo"
          urlDisplayLabel: "Trace: $${__value.raw}"
    secureJsonData:
      httpHeaderValue1: "default"

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://o11y-pyroscope:4040
    access: proxy
    editable: true