http:
  routers:
    home-assistant:
      rule: "Host(`home-assistant.lab.kemo.dev`)"
      entryPoints:
        - websecure
      service: home-assistant
      tls:
        certResolver: stepca

  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://192.168.42.60:8123"
