# Start of converted recursor.yml based on /etc/pdns-recursor/recursor.conf
dnssec:
  validation: off
incoming:
  allow_from:
  - 127.0.0.0/8
  - 10.0.0.0/8
  - 100.64.0.0/10
  - 169.254.0.0/16
  - 192.168.0.0/16
  - 172.16.0.0/12
  - ::1/128
  - fc00::/7
  - fe80::/10
  listen:
  - 0.0.0.0
  port: 53
webservice:
  address: 0.0.0.0
  allow_from:
  - 127.0.0.0/8
  - 192.168.0.0/16
  api_key: $scrypt$ln=10,p=1,r=8$3FikEGu6oTK9kz4S5RAEPg==$Ifkd2fLO/6BWO+dY6zx2V6uLR2S+7VCsfMWe9V0pK78=
  port: 8082
  webserver: true
logging:
  disable_syslog: true
  loglevel: 0
  quiet: true
  trace: on
packetcache:
  negative_ttl: 1
  servfail_ttl: 1
  ttl: 15
recordcache:
  max_cache_bogus_ttl: 1
  max_negative_ttl: 1
  max_ttl: 15
recursor:
  forward_zones:
  - zone: kemo.labs.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: kemo.network.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: kemo.dev.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 10.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 16.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 17.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 18.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 19.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 20.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 21.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 22.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 23.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 24.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 25.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 26.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 27.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 28.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 29.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 30.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 31.172.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 168.192.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 64.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 65.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 66.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 67.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 68.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 69.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 70.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 71.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 72.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 73.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 74.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 75.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 76.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 77.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 78.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 79.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 80.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 81.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 82.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 83.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 84.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 85.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 86.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 87.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 88.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 89.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 90.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 91.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 92.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 93.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 94.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 95.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 96.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 97.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 98.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 99.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 100.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 101.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 102.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 103.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 104.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 105.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 106.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 107.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 108.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 109.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 110.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 111.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 112.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 113.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 114.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 115.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 116.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 117.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 118.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 119.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 120.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 121.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 122.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 123.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 124.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 125.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 126.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  - zone: 127.100.in-addr.arpa.
    recurse: false
    forwarders:
    - 192.168.42.2:5300
  forward_zones_recurse:
  - zone: .
    recurse: true
    forwarders:
    - 192.168.42.4
  nothing_below_nxdomain: no
  security_poll_suffix: ''
  setgid: pdns-recursor
  setuid: pdns-recursor