local-address=0.0.0.0
local-port=53

forward-zones=lab.kemo.dev=192.168.62.2
forward-zones-recurse=.=1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4

allow-from=192.168.62.0/23,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12

webserver=yes
webserver-address=0.0.0.0
webserver-port=8082
api-key=${PDNS_RECURSOR_API_KEY}
