---
x-podman:
  in_pod: false

networks:
  traefik:
    external: true
    name: traefik
  # bridge42:
  #   external: true

volumes:
  uptime-kuma-data:

services:
  uptime-kuma:
    image: ghcr.io/louislam/uptime-kuma@sha256:0f2c9e73cc85cfe97f3ab4781d8d8cb5b35e9b749d21583a2ea381ac28a41461
    container_name: uptime-kuma
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      traefik:
      # bridge42:
      #   ipv4_address: ${STATIC_IP:-192.168.42.32}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.apps.lab.kemo.dev`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=stepca"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "homepage.group=Observability"
      - "homepage.name=Uptime Kuma"
      - "homepage.icon=uptime-kuma.png"
      - "homepage.description='Self-hosted monitoring tool'"
      - "homepage.href=https://uptime.apps.lab.kemo.dev"
