---
x-podman:
  in_pod: false

services:
  vault:
    image: docker.io/hashicorp/vault:1.21
    container_name: vault
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/workdir/caas/vault/data:/vault/data:Z
      - /opt/workdir/caas/vault/logs:/vault/logs:Z
      - ./config:/vault/config:Z
    networks:
      traefik-proxy:
      bridge42:
        ipv4_address: 192.168.42.7
    expose:
      - 8200
      - 8201
    command: vault server -config=/vault/config/vault.hcl
    labels:
      - "dockns.powerdns.record=A"
      - "dockns.powerdns.name=vault.lab.kemo.dev"
      - "dockns.powerdns.ttl=60"
      - "dockns.powerdns.ip=192.168.42.7"
      - "homepage.group=Identity & Secrets"
      - "homepage.name=Vault"
      - "homepage.icon=vault.png"
      - "homepage.description=Vault"
      - "homepage.href=https://vault.apps.lab.kemo.dev"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.vault.rule=Host(`vault.apps.lab.kemo.dev`)"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.tls.certresolver=stepca"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  bridge42:
    external: true
    name: bridge42
  traefik-proxy:
    external: true
    name: traefik-proxy
