# SSL MitM config
http_port 3128 ssl-bump \
  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB \
  cert=/etc/squid/certs/ca-bundle.crt \
  key=/etc/squid/certs/ca.key

http_port 3228 ssl-bump intercept \
  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB \
  cert=/etc/squid/certs/ca-bundle.crt \
  key=/etc/squid/certs/ca.key

# http_port 3328 ssl-bump tproxy \
#   generate-host-certificates=on dynamic_cert_mem_cache_size=16MB \
#   cert=/etc/squid/certs/ca-bundle.crt \
#   key=/etc/squid/certs/ca.key

sslpassword_program /etc/squid/certs/key_password.sh

# no SSL MitM
http_port 3129
http_port 3229 intercept
# http_port 3329 tproxy

# Misc general configuration
visible_hostname proxy.lab.kemo.dev
#dns_v4_first on
forwarded_for on