# SSL MitM config
http_port 3128 ssl-bump \
  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB \
  cert=/etc/squid/certs/ca.crt \
  key=/etc/squid/certs/ca.key \
  cafile=/etc/squid/certs/ca-bundle.crt

#https_port {{ squid_https_intercept_port }} intercept ssl-bump \
#  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB \
#  cert={{ squid_ca_path }}/{{ squid_ca_cert_filename }} \
#  key={{ squid_ca_path }}/{{ squid_ca_key_filename }} \
#  cafile={{ squid_ca_path }}/{{ squid_ca_bundle_filename }}

# no SSL MitM
http_port 3129

# Misc general configuration
visible_hostname proxy.lab.kemo.dev
#dns_v4_first on
forwarded_for on