services:
  it-tools:
    image: docker.io/corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    networks:
      bridge42:
        ipv4_address: 192.168.42.43
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`tools.apps.lab.kemo.dev`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools.tls.certresolver=stepca"
      - "traefik.http.routers.it-tools.service=it-tools"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "homepage.group=Utilities"
      - "homepage.name=IT Tools"
      - "homepage.icon=it-tools.png"
      - "homepage.description='IT Tools'"
      - "homepage.href=https://tools.apps.lab.kemo.dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  bridge42:
    external: true
