name: o11y
x-common: &common
  restart: unless-stopped
  environment:
    - TZ=America/New_York
  networks:
    default:
  logging:
    options:
      max-size: 50m
      max-file: "3"

services:
  #############################################################################################
  # Prometheus Exporter for Podman
  #############################################################################################
  podman-exporter:
    !!merge <<: *common
    # image: prom/prometheus:latest
    image: quay.io/navidys/prometheus-podman-exporter:v1.21.0
    container_name: o11y-podman-exporter
    hostname: o11y-podman-exporter
    security_opt:
      - label=disable
    group_add:
      - 0 # root group to access the podman socket
    volumes:
      - /var/run/podman/podman.sock:/var/run/podman/podman.sock:ro
    environment:
      - CONTAINER_HOST=unix:///var/run/podman/podman.sock
    expose:
      - 9882
    command: ["--collector.enable-all"]

  #############################################################################################
  # Node Exporter for host metrics
  #############################################################################################
  node-exporter:
    !!merge <<: *common
    image: quay.io/prometheus/node-exporter:latest
    container_name: o11y-node-exporter
    hostname: o11y-node-exporter
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - label=disable
    pid: host
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus:/var/run/dbus:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--path.udev.data=/rootfs/run/udev/data'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.diskstats'
      - '--collector.dmi'
      - '--collector.edac'
      - '--collector.filesystem'
      - '--collector.hwmon'
      - '--collector.loadavg'
      - '--collector.meminfo'
      # - '--collector.netclass'
      - '--collector.netdev'
      - '--collector.netstat'
      - '--collector.nvme'
      - '--collector.os'
      - '--collector.processes'
      # - '--collector.pressure'
      - '--collector.stat'
      - '--collector.systemd'
      - '--collector.time'
      - '--collector.thermal_zone'
      - '--collector.uname'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:9100/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  #############################################################################################
  # Loki for Log Aggregation
  #############################################################################################
  loki:
    !!merge <<: *common
    image: docker.io/grafana/loki:latest
    container_name: o11y-loki
    hostname: o11y-loki
    expose:
      - 3100
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_storage:/loki
    command: -config.file=/etc/loki/local-config.yaml
    # healthcheck:
    #   test: ["CMD", "/usr/bin/loki", "-health"]
    #   start_period: 30s
    #   interval: 30s
    #   timeout: 10s
    #   retries: 12

  #############################################################################################
  # Prometheus for Metrics Collection
  #############################################################################################
  prometheus:
    !!merge <<: *common
    # image: prom/prometheus:latest
    image: quay.io/prometheus/prometheus:latest
    container_name: o11y-prometheus
    hostname: o11y-prometheus
    expose:
      - 9090
    networks:
      bridge42:
        ipv4_address: 192.168.42.34
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=stepca"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.apps.lab.kemo.dev`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "homepage.group=Observability"
      - "homepage.name=Prometheus"
      - "homepage.icon=prometheus.png"
      - "homepage.href=https://prometheus.apps.lab.kemo.dev"
      - "homepage.description=Monitoring and Alerting"
    volumes:
      - prometheus_storage:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./config/prometheus/dashboards:/etc/prometheus/dashboards
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=https://prometheus.apps.lab.kemo.dev"
      - "--web.enable-remote-write-receiver"
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --tries=1 --spider http://localhost:9090/metrics']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  #############################################################################################
  # alertmanager to enable receiving alerts
  #############################################################################################
  alertmanager:
    !!merge <<: *common
    image: quay.io/prometheus/alertmanager:latest
    container_name: o11y-alertmanager
    hostname: o11y-alertmanager
    volumes:
      - "./config/alertmanager:/config"
      - alertmanager_storage:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.entrypoints=web,websecure"
      - "traefik.http.routers.alertmanager.service=alertmanager"
      - "traefik.http.routers.alertmanager.tls=true"
      - "traefik.http.routers.alertmanager.tls.certresolver=stepca"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.apps.lab.kemo.dev`)"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "homepage.group=Observability"
      - "homepage.name=Alertmanager"
      - "homepage.icon=alertmanager.png"
      - "homepage.href=https://alertmanager.apps.lab.kemo.dev"
      - "homepage.description=Alert Management"
    expose:
      - 9093
    networks:
      bridge42:
        ipv4_address: 192.168.42.35
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:9093/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  #############################################################################################
  # Pyroscope for Profiling
  #############################################################################################
  pyroscope:
    !!merge <<: *common
    image: docker.io/grafana/pyroscope:latest
    container_name: o11y-pyroscope
    hostname: o11y-pyroscope
    command: ["-self-profiling.disable-push=true"]
    expose:
      - 4040
    volumes:
      - pyroscope_storage:/data/pyroscope

  #############################################################################################
  # Tempo for Traces
  # https://github.com/grafana/tempo/issues/6384
  #############################################################################################
  tempo:
    !!merge <<: *common
    image: docker.io/grafana/tempo:main-8b5ef72
    container_name: o11y-tempo
    hostname: o11y-tempo
    command: [ "-config.file=/etc/tempo.yaml", "-reporting.enabled=false" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo_storage:/var/tempo
    expose:
      - 3200 # tempo
      - 4317 # otlp grpc
      - 14268 # jaeger ingest
      - 9096 # tempo grpc
      - 4318 # otlp http
      - 9411 # zipkin
      - 55678 # opencensus

  #############################################################################################
  # Grafana Image Renderer for PNG Dashboard Exports
  #############################################################################################
  grafana-image-renderer:
    !!merge <<: *common
    image: docker.io/grafana/grafana-image-renderer:latest
    container_name: o11y-grafana-renderer
    hostname: o11y-grafana-renderer
    expose:
      - 8081
    env_file:
      - .env
    environment:
      - ENABLE_METRICS=true
      - AUTH_TOKEN=${GF_RENDERING_RENDERER_TOKEN}

  #############################################################################################
  # Grafana for Dashboards
  #############################################################################################
  grafana:
    !!merge <<: *common
    image: docker.io/grafana/grafana:latest
    container_name: o11y-grafana
    hostname: o11y-grafana
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/dashboards:/data/grafana/dashboards
      - grafana_storage:/var/lib/grafana
    env_file:
      - .env
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_RENDERING_SERVER_URL=http://o11y-grafana-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=https://grafana.apps.lab.kemo.dev/
    expose:
      - 3000
    networks:
      bridge42:
        ipv4_address: 192.168.42.30
    depends_on:
      - prometheus
      - grafana-image-renderer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=stepca"
      - "traefik.http.routers.grafana.rule=Host(`grafana.apps.lab.kemo.dev`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "homepage.group=Observability"
      - "homepage.name=Grafana"
      - "homepage.icon=grafana.png"
      - "homepage.href=https://grafana.apps.lab.kemo.dev"
      - "homepage.description=Dashboards"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL localhost:3000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  prometheus_storage: {}
  alertmanager_storage: {}
  grafana_storage: {}
  loki_storage: {}
  tempo_storage: {}
  pyroscope_storage: {}
  alloy_storage: {}

networks:
  bridge42:
    external: true
  default:
