{
 "title": "grafana-image-renderer",
 "description": "Monitor your grafana-image-renderer deployment.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tempo", "label": "Tempo", "query": "tempo" },
   { "name": "prom", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki", "label": "Loki", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "HTTP server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service HTTP requests in flight",
   "type": "timeseries",
   "description": "How many requests are currently waiting on a response?",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{job=\"image-renderer\"})",
     "legendFormat": "In flight"
    }
   ]
  },
  {
   "title": "Service HTTP request rate",
   "type": "timeseries",
   "description": "How many requests do we get to each Mux path per second?",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(http_request_duration_count{job=\"image-renderer\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Service HTTP response rate",
   "type": "timeseries",
   "description": "How many requests do we get to each Mux path per second?",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, status_code) (increase(http_request_duration_count{job=\"image-renderer\"}[$__rate_interval]))",
     "legendFormat": "{{path}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "Service HTTP request durations (95th percentile)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(path, status_code) (histogram_quantile(0.95, http_request_duration_bucket{job=\"image-renderer\"}))",
     "legendFormat": "{{path}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "Service HTTP request durations (50th percentile)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 8, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum by(path, status_code) (histogram_quantile(0.50, http_request_duration_bucket{job=\"image-renderer\"}))",
     "legendFormat": "{{path}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "Service HTTP panicking requests rate",
   "type": "timeseries",
   "description": "How often do our requests panic?",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(http_recovered_requests_total{job=\"image-renderer\"}[$__rate_interval]))",
     "legendFormat": "Panicking requests"
    }
   ]
  },
  {
   "title": "HTTP rate-limiter slots by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(type) (http_rate_limiter_slots{job=\"image-renderer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP rate-limiter slots by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(result, why) (increase(http_rate_limiter_requests_total{job=\"image-renderer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Browser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "BrowserService durations (p95)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, browser_render_duration_bucket{job=\"image-renderer\", unit=\"seconds\"}))",
     "legendFormat": "BrowserService.Render"
    },
    {
     "expr": "max(histogram_quantile(0.95, browser_render_csv_duration_bucket{job=\"image-renderer\", unit=\"seconds\"}))",
     "legendFormat": "BrowserService.RenderCSV"
    },
    {
     "expr": "max(histogram_quantile(0.95, browser_get_version_duration_bucket{job=\"image-renderer\", unit=\"seconds\"}))",
     "legendFormat": "BrowserService.GetVersion"
    }
   ]
  },
  {
   "title": "Browser Render action durations (p95)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "max by(action) (histogram_quantile(0.95, browser_action_duration_bucket{job=\"image-renderer\", unit=\"seconds\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active browsers over time",
   "type": "timeseries",
   "description": "How many active browsers are there?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(browser_instances_active{job=\"image-renderer\"})",
     "legendFormat": "{{browsers}}"
    }
   ]
  },
  {
   "title": "Chromium memory usage over time",
   "type": "timeseries",
   "description": "This is the peak memory usage reported by each process on every request.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, process_peak_memory_bucket{unit=\"bytes\", job=\"image-renderer\"}))",
     "legendFormat": "p99"
    },
    {
     "expr": "max(histogram_quantile(0.95, process_peak_memory_bucket{unit=\"bytes\", job=\"image-renderer\"}))",
     "legendFormat": "p95"
    },
    {
     "expr": "max(histogram_quantile(0.90, process_peak_memory_bucket{unit=\"bytes\", job=\"image-renderer\"}))",
     "legendFormat": "p90"
    },
    {
     "expr": "max(histogram_quantile(0.50, process_peak_memory_bucket{unit=\"bytes\", job=\"image-renderer\"}))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Chromium memory usage over time",
   "type": "timeseries",
   "description": "The max of any process is the maximum memory any Chromium process has used.\n\nThe peak memory usage over time is how much memory the average process uses. It uses a slow-moving average with decay, thus it takes many requests to move the needle significantly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(process_peak_memory_avg{unit=\"bytes\"})",
     "legendFormat": "peak over time"
    },
    {
     "expr": "max(process_max_memory{unit=\"bytes\"})",
     "legendFormat": "max of any process"
    }
   ]
  },
  {
   "title": "Browser response sizes (p99)",
   "type": "timeseries",
   "description": "How large is a response from each MIME type?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(mime_type) (histogram_quantile(0.99, sum by(le, mime_type) (browser_request_size_bucket{unit=\"bytes\", job=\"image-renderer\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs and traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "All Image Renderer traces",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "filters": [
      { "id": "6b3da378", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "grafana-image-renderer" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"grafana-image-renderer\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Slow traces",
   "type": "table",
   "description": "Where slow means > 5s long.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "filters": [
      { "id": "6b3da378", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "grafana-image-renderer" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      { "id": "duration-type", "value": "trace" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "5s",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"grafana-image-renderer\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "grafana-image-renderer logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"go-build-renderer-.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "grafana-image-renderer interesting logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"go-build-renderer-.*\"} != `level=DEBUG` != `uri=/healthz` != `uri=/metrics` != `uri=/ ` | logfmt"
    }
   ]
  }
 ]
}